#!/bin/sh

set -e


First=`echo $1 | sed 's/\<./\u&/'`
ALL=`echo $1 | sed 's/.*/\U&/'`

cp template.cpp $1.cpp
cp template.hpp $1.hpp

sed -i s/TEMPLATE/$ALL/g $1.cpp $1.hpp
sed -i s/Template/$First/g $1.cpp $1.hpp
sed -i s/template/$1/g $1.cpp $1.hpp
