#!/bin/sh
# check if we are under X-Window
if [ "$DISPLAY" != "" ] && type xmessage >/dev/null 2>&1
then
# type `xlsfonts' and choose your font if you are
# getting message `cannot convert string `9x15bold' to ...'
	case $LANG in 
	"de_AT")
		title="Anzeige von Sammlung"
		font='-*-freesans-medium-r-*-*-*-*-*-*-*-*-u'
		;;
 	*)
		title="Display from Collection"
		font='-*-freesans-medium-r-*-*-*-*-*-*-*-*-u'
		;;
	esac
	xmessage -font $font -title "$title" -background\
	black -bordercolor yellow -foreground yellow -center\
	-xrm '*maxWidth: 800' "`dq $@`" &
else
	tput bold || tput md
	dq  "$@"
	tput sgr0 || tput me
fi
